---
- name: Windows Playbook
  hosts: all

  tasks:
    - name: Include hostname configuration.
      ansible.builtin.import_tasks:
        file: tasks/hostname.yml

    - name: Windows activation.
      ansible.builtin.import_tasks:
        file: tasks/windows-activation.yml

    - name: Include windows updates configuration.
      ansible.builtin.import_tasks:
        file: tasks/updates.yml

    - name: Include debloat configuration.
      ansible.builtin.import_tasks:
        file: tasks/debloat.yml

    - name: Include chocolatey configuration.
      ansible.builtin.import_tasks:
        file: tasks/chocolatey.yml

    - name: Include winget configuration.
      ansible.builtin.import_tasks:
        file: tasks/winget.yml

    - name: Include wsl2 configuration.
      ansible.builtin.import_tasks:
        file: tasks/wsl2.yml

    - name: Include explorer configuration.
      ansible.builtin.import_tasks:
        file: tasks/explorer.yml

    - name: Include taskbar configuration.
      ansible.builtin.import_tasks:
        file: tasks/taskbar.yml

    - name: Include start menu configuration.
      ansible.builtin.import_tasks:
        file: tasks/start_menu.yml

    - name: Include sounds configuration.
      ansible.builtin.import_tasks:
        file: tasks/sounds.yml

    - name: Include mouse configuration.
      ansible.builtin.import_tasks:
        file: tasks/mouse.yml

    - name: Include power plan configuration.
      ansible.builtin.import_tasks:
        file: tasks/power_plan.yml

    - name: Include desktop configuration.
      ansible.builtin.import_tasks:
        file: tasks/desktop.yml
