---
configure_explorer: true
configure_hostname: true
custom_hostname: windows-oscp
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
remove_desktop_icons: true
set_sound_scheme: true

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades
windows_updates_reject_list:
# PB with this update 
  - KB5034441

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

install_chocolatey_packages: true
choco_installed_packages:
  # installs 2.37.1 version of the git
  #- name: git
  #  version: "2.37.1"
  - name: adobereader
    state: latest
  - name: bitwarden
    state: latest  
  - name: googlechrome
    state: latest
  - name: firefox
    state: latest
  - name: git
    state: latest
  - name: microsoft-windows-terminal
    state: latest    
  - name: powertoys
    state: latest
  - name: python3
    state: latest
  - name: vlc
    state: latest
  - name: vmwareworkstation 
    state: latest
    package_params: "'/SERIALNUMBER=4A4RR-813DK-M81A9-4U35H-06KND'"
  - name: vscode
    state: latest     
  
install_winget_packages: true
winget_packages:
  # - name: "Auto Dark Mode"
  #   source: winget
  - name: WinDynamicDesktop
    source: winget

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: true
wsl2_distribution: wsl-ubuntu-2004

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  # - MicrosoftTeams
